### ISSUE TITLE
keyboard shows but not input hindi character

### ISSUE THREAD

**Issue by rahul107** [Firozmemon/Android-Custom-Keyboard#1]
hello  i implementing your keyboard i want only hindi keyboard .
keyboard shows as i want but when i click on character it can't add into the edit text how to solve that?

**Comment by Firozmemon** [comment]
Text inside `Edittext` gets displayed from `onText` method in `BasicOnKeyboardActionListener`

**Comment by rahul107** [comment]
Thanks man, it solved...
