### ISSUE TITLE
can't apply language to multiple edittext

### ISSUE THREAD

**Issue by Abhishekwayindia** [Firozmemon/Android-Custom-Keyboard#2]
As you have one edittext in your project , it is working fine. But how to add this same to multiple edittext

**Comment by Firozmemon** [comment]
I'll try to create with more than one EditText on a separate branch, as soon as possible.

**Comment by Firozmemon** [comment]
#https://github.com/Firozmemon/Android-Custom-Keyboard/commit/6779718a44b1a693022910edd50c9f7f72390cec Added support for 2 EditText's
